./bin/SeekRe ./examples/inputs/mwc/MWC00.dat > ./examples/inputs/mwc/MWC00.res
./bin/SeekRe ./examples/inputs/mwc/MWC01.dat > ./examples/inputs/mwc/MWC01.res
./bin/SeekRe ./examples/inputs/mwc/MWC02.dat > ./examples/inputs/mwc/MWC02.res
./bin/SeekRe ./examples/inputs/mwc/MWC03.dat > ./examples/inputs/mwc/MWC03.res
./bin/SeekRe ./examples/inputs/mwc/MWC04.dat > ./examples/inputs/mwc/MWC04.res
./bin/SeekRe ./examples/inputs/mwc/MWC05.dat > ./examples/inputs/mwc/MWC05.res
./bin/SeekRe ./examples/inputs/mwc/MWC06.dat > ./examples/inputs/mwc/MWC06.res
./bin/SeekRe ./examples/inputs/mwc/MWC07.dat > ./examples/inputs/mwc/MWC07.res
./bin/SeekRe ./examples/inputs/mwc/MWC08.dat > ./examples/inputs/mwc/MWC08.res
./bin/SeekRe ./examples/inputs/mwc/MWC09.dat > ./examples/inputs/mwc/MWC09.res
./bin/SeekRe ./examples/inputs/mwc/MWC10.dat > ./examples/inputs/mwc/MWC10.res
