#!/usr/bin/env python
# coding: utf-8

def build(ctx):

    lc_inc_dir = ctx.path.parent.find_dir('latticetester/include')
    lm_inc_dir = ctx.path.parent.find_dir('include')

    for src, tgt in [('SeekMain.cc', 'seek'), ('LatMain.cc', 'lat')]:
        ctx(features='cxx cxxprogram',
                source=ctx.path.find_node(src),
                includes=[lm_inc_dir, lc_inc_dir],
                lib=ctx.env.LIB_NTL + ctx.env.LIB_TESTU01 + ctx.env.LIB_GMP + ctx.env.LIB_MYLIB,
                stlib=ctx.env.STLIB_NTL + ctx.env.STLIB_TESTU01 + ctx.env.STLIB_GMP + ctx.env.STLIB_MYLIB,
                target=(tgt + ctx.env.LATTICETESTER_SUFFIX),
                use=['latmrg' + ctx.env.LATTICETESTER_SUFFIX, 'latcommon' + ctx.env.LATTICETESTER_SUFFIX],
                install_path='${BINDIR}')

    if ctx.env.LATTICETESTER_SUFFIX == 'ZZDD':
        for src, tgt in [('MaxPeriod.cc', 'maxper'), ('FindMK.cc', 'findmk'), ('FindMK2.cc', 'findmk2')]:
            ctx(features='cxx cxxprogram',
                    source=ctx.path.find_node(src),
                    includes=[lm_inc_dir, lc_inc_dir],
                    lib=ctx.env.LIB_NTL + ctx.env.LIB_TESTU01 + ctx.env.LIB_GMP + ctx.env.LIB_MYLIB,
                    stlib=ctx.env.STLIB_NTL + ctx.env.STLIB_TESTU01 + ctx.env.STLIB_GMP + ctx.env.STLIB_MYLIB,
                    target=tgt,
                    use=['latmrgZZDD', 'latcommonZZDD'],
                    install_path='${BINDIR}')