LatMRG API Documentation: latticetester/include/latticetester/Random.h File Reference
Random.h File Reference
This file offers functions to generate random numbers use when making random searches.
#include <cstdint>
#include <climits>
#include <NTL/ZZ.h>
Namespaces
namespace LatticeTester
LatticeTester namespace.
Macros
#define GERME (ULONG_MAX / 54321)
Functions
double LatticeTester::Random::randU01 ()
Returns a random number in \([0, 1)\).
std::int64_t LatticeTester::Random::randInt (std::int64_t i, std::int64_t j)
Return a random integer in \([i, j]\).
NTL::ZZ LatticeTester::Random::randInt (NTL::ZZ i, NTL::ZZ j)
This is an overload of the previous method to create an NTL::ZZ integer in the range \([i,j]\).
std::uint64_t LatticeTester::Random::randBits (int64_t s)
Returns random blocks of \(s\) bits (\(s\)-bit integers).
void LatticeTester::Random::setSeed (std::uint64_t seed=GERME)
Sets the seed of the generator.
Detailed Description
This file offers functions to generate random numbers use when making random searches.
The base generator is the 64-bit LFSR258 from [rLEC99a], with period near \(2^{258}\), for 64-bit computers, and the 32-bit generator LFSR113 from [rLEC99a], with period length near \(2^{113}\) on 32-bits computers. Thus the random numbers are different on 32-bits and 64-bits machines.
Function Documentation
randInt() [1/2]
NTL::ZZ LatticeTester::Random::randInt (NTL::ZZ i, NTL::ZZ j)
This is an overload of the previous method to create an NTL::ZZ integer in the range \([i,j]\).
NTL has a method to generate pseudo random numbers in a given range, but it is not deterministic. This method concatenates random bits until it has a big enough number and tries to assign the correct integer to it.
References LatticeTester::Random::randInt().
randInt() [2/2]
std::int64_t LatticeTester::Random::randInt (std::int64_t i, std::int64_t j)
Return a random integer in \([i, j]\).
The numbers \(i\) and \(j\) can occur. Restriction: \(i < j\). The generated number is limited to 62 bits.
References LatticeTester::Random::randInt().
Referenced by LatticeTester::Random::randInt(), and LatticeTester::Random::randInt().
randU01()
double LatticeTester::Random::randU01 ()
Returns a random number in \([0, 1)\).
The number has 53 random bits of resolution on 64-bits machines, and 32 random bits on 32-bits machines.
References LatticeTester::Random::randU01().
Referenced by LatticeTester::Random::randU01().
setSeed()
void LatticeTester::Random::setSeed (std::uint64_t seed = GERME)
Sets the seed of the generator.
If not called, a default seed is used.
References LatticeTester::Random::setSeed().
Referenced by LatticeTester::Random::setSeed().