#!/usr/bin/env python
# coding: utf-8

def build(ctx):
    src_dir = ctx.path.parent.find_dir('examples/')
    inc_dir = ctx.path.find_dir('../include')
    inc_dir2 = ctx.path.find_dir('../latticetester/include')
    latticetester_src = ctx.path.find_dir('../latticetester/src').ant_glob('*.cc')
    ctx.add_group('group3')
    ctx.add_group('group4')
    ctx.add_group('group5')
    
    ctx.set_group('group3')
    for src in ctx.path.ant_glob('*.cc'):
        ctx(features='cxx cxxprogram',
                source=[src] + latticetester_src,
                includes=[inc_dir,inc_dir2,'../latticetester/src'],
                lib=ctx.env.LIB_NTL + ctx.env.LIB_GMP, 
                stlib=ctx.env.STLIB_NTL + ctx.env.STLIB_GMP,
                target=src.name[:-3],
                use=['latmrg'],
                install_path='${BINDIR}/examples')

    ctx.set_group('group4')
    for src in ctx.path.ant_glob('build/examples/*.o'):
        ctx(rule='rm ${SRC}',
                source=src,
                target=src.name[:],
                use=src.name[:-6] + 'cc',
                install_path='${BINDIR}/examples')
        
    ctx.set_group('group5')
    for src in ctx.path.ant_glob('*.dat'):
        ctx(rule='cp ${SRC} ${TGT}',
                source=src,
                target=src.name[:],
                install_path='${BINDIR}/examples')

    for src in ctx.path.ant_glob('*.zip'):
        ctx(rule='cp ${SRC} ${TGT}',
                source=src,
                target=src.name[:],
                install_path='${BINDIR}/examples')
